---
title: "Informe recurrencia"
author: "Illak Zapata"
date: "2022-09-11"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

```{r librerias}
library(tidyverse)
library(ggtext)
library(glue)
library(patchwork)

```

```{r datos}
datos <- read_csv("data/datos_v4.csv")
datos_agrupaciones <- read_csv("data/agrupaciones.csv")


```



```{r recurrencia general, fig.width=11, fig.asp=0.8}
datos_categorias <- datos %>% 
  mutate(
    periodo = case_when(
      cohorte_anio == 2016 ~ "2016",
      cohorte_anio == 2017 ~ "2017",
      cohorte_anio == 2018 ~ "2018",
      cohorte_anio == 2019 ~ "2019",
      cohorte_anio == 2020 ~ "2020",
      cohorte_anio == 2021 ~ "2021",
      cohorte_anio == 2022 ~ "2022"),
    periodo = factor(periodo, levels = c("2016","2017","2018","2019","2020","2021","2022")),
  ) %>% 
  select(idpersona, periodo) %>% 
  distinct() %>% 
  group_by(idpersona) %>% 
  arrange(periodo) %>% 
  mutate(prev = lag(periodo)) %>% 
  ungroup()




lineas_verticales_alturas <- datos_categorias %>% 
  filter(!is.na(prev)) %>% 
  group_by(periodo) %>% 
  summarise(altura = n_distinct(idpersona)) %>% 
  pull(altura)

lineas_verticales_pos <- c(2.35,3.35,4.35,5.35,6.35,7.35)

lineas_v <- data.frame(
  x = lineas_verticales_pos,
  xend = lineas_verticales_pos,
  y = 0,
  yend = lineas_verticales_alturas
)

lineas_h <- data.frame(
  x = c(2.3,3.3,4.3,5.3,6.3,7.3),
  xend = c(2.4,3.4,4.4,5.4,6.4,7.4),
  y = lineas_verticales_alturas,
  yend = lineas_verticales_alturas
)

porcentajes <- datos_categorias %>% 
  filter(periodo != "2016") %>% 
  group_by(periodo) %>% 
  summarise(total = n_distinct(idpersona),
            recurrentes = n_distinct(idpersona[!is.na(prev)])) %>% 
  mutate(pct = recurrentes / total) %>% 
  pull(pct)

porcentajes_df <- data.frame(
  label = porcentajes,
  x = c(2.4,3.4,4.4,5.4,6.4,7.4),
  y = lineas_verticales_alturas / 2
)

(recurrencia_periodos_plot <- datos_categorias %>% 
    group_by(periodo) %>% 
    summarise(nuevas = n_distinct(idpersona[is.na(prev)]),
              recurrentes = n_distinct(idpersona[!is.na(prev)])) %>% 
    ungroup() %>% 
    pivot_longer(cols = c(nuevas, recurrentes), names_to = "categoria", values_to = "n") %>% 
    filter(n > 0) %>% 
    mutate(periodo_mod = glue("<i>{periodo}</i>")) %>% 
    ggplot(aes(x = periodo_mod, y = n)) +
    geom_col(aes(fill = categoria), width = .5, color = "black") +
    geom_text(aes(label = n, group = categoria), position=position_stack(vjust=0.5)) +
    geom_segment(data = lineas_v, mapping = aes(x = x, xend = xend, y = y, yend = yend),
                 size = .5, linetype = "dashed", color = "grey50") +
    geom_segment(data = lineas_h, mapping = aes(x = x, xend = xend, y = y, yend = yend),
                 size = .5, color = "grey50") +
    geom_label(data = porcentajes_df, 
              mapping = aes(label = scales::percent(label, accuracy = 1), x = x -.1, y = y), 
              hjust = 0, size = 4, color = "grey30") +
    scale_y_continuous(breaks = seq(0,10000,2000)) +
    ggthemes::scale_fill_tableau() +
    ggtitle("Recurrencia general") +
    coord_cartesian(clip = "off") +
    guides(fill = "none") +
    labs(y = NULL, x = NULL,
         subtitle = "Personas que registran matrícula por <i style='color:#4E79A7'>primera vez</i> y personas <i style='color:#F28E2B'>recurrentes</i>") +
    theme_minimal(base_size = 17) +
    theme(
      axis.text.x = element_markdown(),
      plot.title.position = "plot",
      legend.position = "top",
      plot.margin = margin(5,10,5,5,unit="mm"),
      plot.subtitle = element_markdown(color = "grey40")
    ))

```

```{r recurrencia x grupo, fig.width=11, fig.asp=0.8}

datos_personas <- datos %>% 
  mutate(
    periodo = case_when(
      cohorte_anio %in% c(2016) ~ "2016",
      cohorte_anio %in% c(2017) ~ "2017",
      cohorte_anio %in% c(2018) ~ "2018",
      cohorte_anio %in% c(2019) ~ "2019",
      cohorte_anio %in% c(2020) ~ "2020",
      cohorte_anio %in% c(2021) ~ "2021",
      cohorte_anio %in% c(2022) ~ "2022"),
    periodo = factor(periodo, levels = c("2016","2017","2018","2019","2020","2021","2022"))
  ) %>% 
  left_join(datos_agrupaciones)


analisis_grupo <- function(filtro){
  
  datos_personas %>% 
    filter(grupo == {{filtro}}) %>% 
    group_by(idpersona) %>% 
    arrange(periodo) %>% 
    mutate(prev = lag(periodo)) %>% 
    ungroup()
  
}

filtros <- datos_agrupaciones %>% 
  pull(grupo) %>% 
  unique()

dfs <- map_df(filtros, analisis_grupo)

recurrencia_x_grupo <- dfs %>% 
  mutate(grupo = str_wrap(grupo, width = 30)) %>% 
  group_by(grupo, periodo) %>% 
  summarise(nuevas = n_distinct(idpersona[is.na(prev)]),
            recurrentes = n_distinct(idpersona[!is.na(prev)])) %>% 
  pivot_longer(cols = c(nuevas, recurrentes), names_to = "categoria", values_to = "n") %>% 
  ggplot(aes(x = periodo, y = n, fill=categoria)) +
  geom_col() +
  ggthemes::scale_fill_tableau() +
  labs(y = NULL, x = NULL) +
  guides(fill = "none") +
  ggtitle("Recurrencia al interior de cada grupo de propuestas") +
  facet_wrap(vars(grupo)) +
  theme_minimal(base_size = 17) +
  theme(
    strip.background = element_rect(color = "black"),
    strip.text = element_text(size = 12),
    plot.title.position = "plot",
    axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
    plot.margin = margin(5,5,5,10)
  )

recurrencia_x_grupo


```



